spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
      open-in-view: false
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always
      platform: h2
      scripts: classpath:schema.sql,classpath:data.sql
      
      
  data:
     rest:
       base-path: /data-api
       
  security: 
     oAuth2:
       resourceserver:
         jwt:jwk-set-uri: http://localhost:9000/oauth2/jwks
           

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE
      springframework:
        security: DEBUG
        oauth2: DEBUG
    root: INFO
    tacos: DEBUG
    
security:
  oauth2:
    client:
      registration:
        facebook:
          clientId: 2291618721048050
          clientSecret: cf8d0e9f46ae20835b47d8a3f3d4d18e
          scope: email, public_profile
          
server:
  port: 9000
